In [38]:
import pandas as pd
import json

data_folder_path = "/Users/lukajin/PycharmProjects/soamp/data/"

In [39]:
df = pd.read_csv(data_folder_path + "mic_classification_dataset.csv")

In [40]:
df.head()

,peptide_id,sequence,smiles,organism,ncbi_taxon_id_if_available,mic_value_uM,mic_type,has_noncanonical,label,split
0,10,LFIFFF,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C...,Staphylococcus aureus,1280,15.60,censored,False,active,train
1,11,RVKRVWPLVIRTVIAGYNLYRAIKKK,CC[C@H](C)[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCCN...,Escherichia coli,562,2.24,averaged,False,active,train
2,11,RVKRVWPLVIRTVIAGYNLYRAIKKK,CC[C@H](C)[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCCN...,Pseudomonas aeruginosa,287,5.06,averaged,False,active,train
3,11,RVKRVWPLVIRTVIAGYNLYRAIKKK,CC[C@H](C)[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCCN...,Staphylococcus aureus,1280,1.11,averaged,False,active,train
4,12,RKRIHIGPGRAFYTT,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)...,Escherichia coli,562,6.76,averaged,False,active,test

In [41]:
df['split'].value_counts()

split
train    17043
test      7587
Name: count, dtype: int64

In [29]:
train_folds = pd.read_csv(data_folder_path + "train_folds_leiden.csv")

In [30]:
train_folds['fold_id'].value_counts()

fold_id
4    3497
1    3488
3    3397
2    3366
0    3295
Name: count, dtype: int64

In [31]:
train_df = df[df['split'] != 'test']

In [32]:
train_df.head()

,peptide_id,sequence,smiles,organism,ncbi_taxon_id_if_available,mic_value_uM,mic_type,has_noncanonical,label,split
0,10,LFIFFF,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C...,Staphylococcus aureus,1280,15.60,censored,False,active,train
1,11,RVKRVWPLVIRTVIAGYNLYRAIKKK,CC[C@H](C)[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCCN...,Escherichia coli,562,2.24,averaged,False,active,train
2,11,RVKRVWPLVIRTVIAGYNLYRAIKKK,CC[C@H](C)[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCCN...,Pseudomonas aeruginosa,287,5.06,averaged,False,active,train
3,11,RVKRVWPLVIRTVIAGYNLYRAIKKK,CC[C@H](C)[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCCN...,Staphylococcus aureus,1280,1.11,averaged,False,active,train
8,15,DSHAKRHHGYKRKFHEKHHSHRGY,C[C@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](CO)...,Staphylococcus aureus,1280,132.00,censored,False,inactive,train

In [33]:
train_folds

       node_id  community  fold_id
0            8          0        2
1            9          0        2
2           19          0        2
3           20          0        2
4           21          0        2
...        ...        ...      ...
17038    16945       1320        0
17039    16958       1321        1
17040    16967       1322        3
17041    16970       1323        3
17042    17014       1324        2

[17043 rows x 3 columns]

In [34]:
fold_columns = ['node_id', 'fold_id']
train_columns = ['peptide_id', 'organism', 'has_noncanonical', 'label']

In [35]:
train_df = pd.merge(train_folds[fold_columns], train_df[train_columns], left_on='node_id', right_on='peptide_id', how='inner')

In [36]:
train_df

,node_id,fold_id,peptide_id,organism,has_noncanonical,label
0,79,2,79,Staphylococcus aureus,False,active
1,79,2,79,Escherichia coli,False,active
2,79,2,79,Pseudomonas aeruginosa,False,active
3,80,2,80,Staphylococcus aureus,False,active
4,80,2,80,Escherichia coli,False,active
...,...,...,...,...,...,...
12262,16945,0,16945,Escherichia coli,True,active
12263,16945,0,16945,Staphylococcus aureus,True,inactive
12264,16958,1,16958,Escherichia coli,False,active
12265,16958,1,16958,Pseudomonas aeruginosa,False,active
12266,16958,1,16958,Staphylococcus aureus,False,active